name: Batch Feedback Trend Analysis

on:
  schedule:
    - cron: '0 9 */14 * *'          # Every 14 days at 9:00 UTC (change as needed)
  workflow_dispatch:                # Allows manual trigger

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run batch analysis
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          PRODUCTBOARD_API_TOKEN: ${{ secrets.PRODUCTBOARD_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PRODUCT_TEAM_CHANNEL: ${{ secrets.PRODUCT_TEAM_CHANNEL }}
        run: python batch_analysis.py
